export const state = {
  levelsConfig: [],
  allLevelFiles: [],
  currentLevel: null,
  currentLevelId: null,
  cellSize: 44,
  zoom: 1,
  panX: 0,
  panY: 0,
  isDragging: false,
  dragStartX: 0,
  dragStartY: 0,
  dragPanX: 0,
  dragPanY: 0,
  selectedElement: null,
  modified: false,
  isCustomLevel: false,
  customLevels: [],
  doorStates: {},
  renderState: { offsetX: 0, offsetY: 0, gridW: 0, gridH: 0, ox: 0, oy: 0, cellSize: 44 },
  editMode: 'play',
  activeTool: 'cell',
  activeFilter: 'all',
  dragMode: 'none',
  dragMoved: false,
  moveTarget: null,
  lastMoveValid: true,
  moveViolation: '',
};
